# Generated by Django 6.0.2 on 2026-07-02 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommStaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=256)),
            ],
            options={
                "verbose_name": "Comm Center staff member",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DutyOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=256)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=16, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("RW", "Rotor Wing"), ("GR", "Ground Trucks")],
                        max_length=2,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "current_status",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "display_order", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("weather", models.CharField(blank=True, default="", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "permissions": [
                    ("reopen_report", "Can reopen a submitted AOC daily report")
                ],
            },
        ),
        migrations.CreateModel(
            name="CrewEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("BED", "Bedford"),
                            ("PYM", "Plymouth"),
                            ("LWM", "Lawrence"),
                            ("MAN", "Mansfield"),
                            ("MHT", "Manchester"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "shift_code",
                    models.CharField(
                        choices=[
                            ("D11H", "D11H"),
                            ("D11M", "D11M"),
                            ("D7B", "D7B"),
                            ("D7P", "D7P"),
                            ("D9L", "D9L"),
                            ("GR", "GR"),
                            ("LG", "LG"),
                            ("MG", "MG"),
                            ("N7B", "N7B"),
                            ("N7P", "N7P"),
                            ("N9L", "N9L"),
                            ("NG", "NG"),
                            ("NL", "NL"),
                            ("NP", "NP"),
                            ("PG", "PG"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("RN", "RN"),
                            ("EMTP", "EMTP"),
                            ("PILOT", "Pilot"),
                            ("EMT", "EMT"),
                        ],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "ref_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Marks a confirmed open position (renders OPEN).",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_entries",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crew entries",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExtraEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BED", "Bedford"),
                            ("PYM", "Plymouth"),
                            ("LWM", "Lawrence"),
                            ("MAN", "Mansfield"),
                            ("MHT", "Manchester"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                (
                    "shift_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D11H", "D11H"),
                            ("D11M", "D11M"),
                            ("D7B", "D7B"),
                            ("D7P", "D7P"),
                            ("D9L", "D9L"),
                            ("GR", "GR"),
                            ("LG", "LG"),
                            ("MG", "MG"),
                            ("N7B", "N7B"),
                            ("N7P", "N7P"),
                            ("N9L", "N9L"),
                            ("NG", "NG"),
                            ("NL", "NL"),
                            ("NP", "NP"),
                            ("PG", "PG"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RN", "RN"),
                            ("EMTP", "EMTP"),
                            ("PILOT", "Pilot"),
                            ("EMT", "EMT"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("note", models.CharField(blank=True, default="", max_length=256)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_entries",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Extra entries",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MissCategoryCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(blank=True, default="", max_length=64)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miss_counts",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Miss category counts",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PendingTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("call_type", models.CharField(blank=True, default="", max_length=64)),
                ("asset", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("location", models.CharField(blank=True, default="", max_length=128)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_transports",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReportAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("reopened", "Reopened"),
                            ("email_sent", "Email sent"),
                            ("email_failed", "Email failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SickLateEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("sick_call", "Sick call"),
                            ("late_arrival", "Late arrival"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sick_late_entries",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sick / late entries",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TransportSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pending_count", models.PositiveIntegerField(default=0)),
                (
                    "complex_calls",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Complex / complicated logistical calls",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_summary",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transport summaries",
            },
        ),
        migrations.CreateModel(
            name="VehicleStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, default="", max_length=128)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="crew_hub.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="CommShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "seat",
                    models.CharField(
                        choices=[
                            ("D", "D"),
                            ("D2", "D-2"),
                            ("S", "S"),
                            ("S2", "S-2"),
                            ("S3", "S-3"),
                            ("N", "N"),
                            ("N2", "N-2"),
                            ("P", "P"),
                            ("P2", "P-2"),
                            ("EXTRA", "Orientee / Extra"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text name when the person is not in the roster.",
                        max_length=128,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=256)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crew_hub.commstaffmember",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "seat"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "seat"), name="uniq_comm_seat_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommCenterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat",
                    models.CharField(
                        choices=[
                            ("D", "D"),
                            ("D2", "D-2"),
                            ("S", "S"),
                            ("S2", "S-2"),
                            ("S3", "S-3"),
                            ("N", "N"),
                            ("N2", "N-2"),
                            ("P", "P"),
                            ("P2", "P-2"),
                            ("EXTRA", "Orientee / Extra"),
                        ],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_entries",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comm Center entries",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "seat"), name="uniq_comm_entry_per_report"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DutyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AOC", "AOC"),
                            ("AAOC", "AAOC"),
                            ("MDOC", "MDOC"),
                            ("PEDIDOC", "PediDOC"),
                            ("ITOC", "ITOC"),
                            ("BPM", "BPM"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text name when the person is not in the roster.",
                        max_length=128,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=256)),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crew_hub.dutyofficer",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "role", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "role", "officer"),
                        name="uniq_duty_assignment_officer",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DutyRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AOC", "AOC"),
                            ("AAOC", "AAOC"),
                            ("MDOC", "MDOC"),
                            ("PEDIDOC", "PediDOC"),
                            ("ITOC", "ITOC"),
                            ("BPM", "BPM"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_entries",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Duty roster entries",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "role"), name="uniq_duty_entry_per_report"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransportBaseCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("BED", "Bedford"),
                            ("PYM", "Plymouth"),
                            ("LWM", "Lawrence"),
                            ("MAN", "Mansfield"),
                            ("MHT", "Manchester"),
                        ],
                        max_length=4,
                    ),
                ),
                ("gcct", models.PositiveIntegerField(default=0)),
                ("rw", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_base_counts",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "base"), name="uniq_transport_base_per_report"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleStatusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.CharField(max_length=16)),
                (
                    "category",
                    models.CharField(
                        choices=[("RW", "Rotor Wing"), ("GR", "Ground Trucks")],
                        max_length=2,
                    ),
                ),
                ("status", models.CharField(blank=True, default="", max_length=128)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_entries",
                        to="crew_hub.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle status entries",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "vehicle_id"),
                        name="uniq_vehicle_entry_per_report",
                    )
                ],
            },
        ),
    ]
