# Generated by Django 6.0.2 on 2026-07-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew_hub", "0002_commshiftassignment_work_type_commrotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyassignment",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("sick", "Sick leave"),
                    ("swap", "Swap"),
                    ("overtime", "Overtime"),
                ],
                default="regular",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="DutyRotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("cycle", "Cycle (days on / days off)"),
                            ("weekly", "Weekly (fixed weekdays)"),
                        ],
                        default="cycle",
                        max_length=8,
                    ),
                ),
                ("days_on", models.PositiveSmallIntegerField(default=4)),
                ("days_off", models.PositiveSmallIntegerField(default=4)),
                ("weekdays", models.CharField(blank=True, default="", max_length=32)),
                (
                    "anchor_date",
                    models.DateField(
                        help_text="First day of the pattern (cycle day 1 / first active week)."
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional last day the rotation applies.",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=256)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AOC", "AOC"),
                            ("AAOC", "AAOC"),
                            ("MDOC", "MDOC"),
                            ("PEDIDOC", "PediDOC"),
                            ("ITOC", "ITOC"),
                            ("BPM", "BPM"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations",
                        to="crew_hub.dutyofficer",
                    ),
                ),
            ],
            options={
                "ordering": ["officer__name", "role"],
            },
        ),
    ]
