# Generated by Django 6.0.2 on 2026-07-02 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crew_hub", "0003_dutyassignment_work_type_dutyrotation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyreport",
            options={
                "ordering": ["-report_date"],
                "permissions": [
                    ("reopen_report", "Can reopen a submitted AOC daily report"),
                    (
                        "manage_schedules",
                        "Can edit Crew Hub schedules, rotations, rosters, and vehicle statuses",
                    ),
                ],
            },
        ),
    ]
