# Generated by Django 5.2.15 on 2026-07-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew_hub", "0007_permission_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyofficer",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AOC", "AOC"),
                    ("AAOC", "AAOC"),
                    ("MDOC", "MDOC"),
                    ("PEDIDOC", "PediDOC"),
                    ("ITOC", "ITOC"),
                    ("BPM", "BPM"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
