# Generated by Django 5.2.16 on 2026-07-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew_hub", "0009_calendar_feed_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commrotation",
            name="pattern_type",
            field=models.CharField(
                choices=[
                    ("cycle", "Cycle (days on / days off)"),
                    ("weekly", "Weekly (fixed weekdays)"),
                    ("pitman", "2-2-3 Pitman (7 shifts / 2 weeks)"),
                ],
                default="cycle",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="dutyrotation",
            name="pattern_type",
            field=models.CharField(
                choices=[
                    ("cycle", "Cycle (days on / days off)"),
                    ("weekly", "Weekly (fixed weekdays)"),
                    ("pitman", "2-2-3 Pitman (7 shifts / 2 weeks)"),
                ],
                default="cycle",
                max_length=8,
            ),
        ),
    ]
