# Generated by Django 5.2.16 on 2026-07-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew_hub", "0010_alter_commrotation_pattern_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commshiftassignment",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("sick", "Sick leave"),
                    ("swap", "Swap"),
                    ("overtime", "Overtime"),
                    ("leave", "Leave (LOA)"),
                ],
                default="regular",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="dutyassignment",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("sick", "Sick leave"),
                    ("swap", "Swap"),
                    ("overtime", "Overtime"),
                    ("leave", "Leave (LOA)"),
                ],
                default="regular",
                max_length=16,
            ),
        ),
    ]
