# Generated by Django 6.0.7 on 2026-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew_hub", "0012_alter_commshiftassignment_work_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commshiftassignment",
            options={"ordering": ["date", "seat", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="commshiftassignment",
            name="uniq_comm_seat_day",
        ),
        migrations.AddField(
            model_name="commshiftassignment",
            name="hours",
            field=models.FloatField(
                blank=True,
                help_text="Paid hours for this person on this day. Blank uses the slot's standard hours.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dutyassignment",
            name="hours",
            field=models.FloatField(
                blank=True,
                help_text="Paid hours for this person on this day. Blank uses the slot's standard hours.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commshiftassignment",
            name="seat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "D"),
                    ("D2", "D-2"),
                    ("S", "S"),
                    ("S2", "S-2"),
                    ("S3", "S-3"),
                    ("N", "N"),
                    ("N2", "N-2"),
                    ("P", "P"),
                    ("P2", "P-2"),
                    ("EXTRA", "Orientee / Extra"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="dutyassignment",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AOC", "AOC"),
                    ("AAOC", "AAOC"),
                    ("MDOC", "MDOC"),
                    ("PEDIDOC", "PediDOC"),
                    ("ITOC", "ITOC"),
                    ("BPM", "BPM"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
