# Generated by Django 4.2.23 on 2026-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagerRosterLastName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "Manager roster (last name)",
                "verbose_name_plural": "Manager roster (last names)",
                "db_table": "manager_roster_last_name",
                "managed": False,
            },
        ),
    ]
