# Generated by Django 6.0.8 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_weekly_staffing_unpartnered_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffRosterEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=128)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("role", models.CharField(max_length=16)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.CharField(blank=True, max_length=32, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Staff roster entry",
                "verbose_name_plural": "Staff roster entries",
                "db_table": "staff_roster_entry",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrainingCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("created_at", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "verbose_name": "Training code",
                "verbose_name_plural": "Training codes",
                "db_table": "training_code",
                "managed": False,
            },
        ),
    ]
