from .accounts import user_admin
from .hub import hub_home
from .me import (
    calendar_feed,
    calendar_feed_reset,
    my_schedule,
    notifications,
    notifications_read,
    time_off_decide,
    time_off_manage,
    time_off_submit,
)
from .payroll_views import hours_report, hours_report_csv
from .report import (
    report_detail,
    report_html,
    report_list,
    report_preview,
    report_refresh,
    report_reopen,
    report_save,
    report_submit,
    report_today,
)
from .rotations import (
    api_comm_move,
    api_comm_remove,
    api_comm_reseat,
    api_comm_work_type,
    api_duty_move,
    api_duty_remove,
    api_duty_work_type,
    comm_rotations,
    comm_rotations_apply,
    duty_rotations,
    duty_rotations_apply,
)
from .schedulers import (
    comm_day,
    comm_month,
    comm_staff,
    duty_day,
    duty_month,
    duty_roster,
)
from .vehicles import vehicle_board

__all__ = [
    "api_comm_move",
    "calendar_feed",
    "calendar_feed_reset",
    "api_comm_remove",
    "api_comm_reseat",
    "api_comm_work_type",
    "api_duty_move",
    "api_duty_remove",
    "api_duty_work_type",
    "comm_day",
    "comm_month",
    "comm_rotations",
    "comm_rotations_apply",
    "comm_staff",
    "duty_rotations",
    "duty_rotations_apply",
    "hours_report",
    "hours_report_csv",
    "my_schedule",
    "notifications",
    "notifications_read",
    "time_off_decide",
    "time_off_manage",
    "time_off_submit",
    "duty_day",
    "duty_month",
    "duty_roster",
    "hub_home",
    "report_detail",
    "report_html",
    "report_list",
    "report_preview",
    "report_refresh",
    "report_reopen",
    "report_save",
    "report_submit",
    "report_today",
    "user_admin",
    "vehicle_board",
]
